# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - goos:
    - darwin
    - linux
    goarch:
    - arm
    - arm64
    - amd64
    goarm:
    - 6
    - 7
    ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    env:
    - CGO_ENABLED=0
archive:
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ time "20060102_150405" }}-{{ .ShortCommit }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
